HyperPlay-Gaming/hyperplay-desktop-client

- README.md
- src/backend/config.ts
- src/frontend/components/UI/StoreFilter/index.tsx
> FIX: ReadMe and fixes

- public/locales/en/translation.json
- src/frontend/browserGame/BrowserExtensionToastManager/index.tsx
- src/frontend/browserGame/BrowserToastManager/index.tsx
- src/frontend/screens/TransactionNotification/constants.ts
- src/frontend/screens/TransactionNotification/index.tsx
This fixes toast texts reading as undefined after using i18n to translate
---
> [Fix] Toast Text 

- package.json
- public/webviewPreload.js
- src/backend/api/misc.ts
- src/backend/gog/games.ts
- src/backend/gog/library.ts
- src/backend/legendary/games.ts
- src/backend/legendary/library.ts
- src/backend/main.ts
- src/backend/utils.ts
- src/common/typedefs/ipcBridge.d.ts
- src/common/types.ts
- src/common/types/legendary.ts
- src/frontend/components/UI/Sidebar/components/CurrentDownload/index.tsx
- src/frontend/components/UI/Sidebar/index.tsx
- src/frontend/hooks/hasProgress.ts
- src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
- src/frontend/screens/Game/GamePage/index.scss
- src/frontend/screens/Game/GamePage/index.tsx
- src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
- src/frontend/screens/WebView/index.tsx
This fixes the sidebar dragging not working on webviews and some other fixes and improvements from Heroic.
---
> [FIX] Sidebar Drag fix + Pull fixes from Heroic

- src/backend/storeManagers/hyperplay/library.ts
- src/backend/storeManagers/hyperplay/utils.ts
- src/common/types.ts
* fix: incorrect card images being shown
* fix: optimized hyperplay refresh method
* feat: implemented accountMeta from valist API
---
> [Tech] Performance improvement & valist metadata updates

- src/backend/hyperplay_store_preload.ts
> [Fix] openExternalUrl to store preload

- package.json
- public/locales/en/translation.json
- src/frontend/screens/Library/components/InstallModal/SideloadDialog/Warning/index.module.scss
- src/frontend/screens/Library/components/InstallModal/SideloadDialog/Warning/index.tsx
- src/frontend/screens/Library/components/InstallModal/SideloadDialog/index.tsx
- yarn.lock
> [UI] added alert card to add-sideload-game modal

- src/frontend/ExtensionManager/index.tsx
> refactor: refresh element instead of removing element

- src/frontend/screens/MetaMaskPortfolio/index.tsx
The MetaMask portfolio page relies on the ability to create popups in order to purchase/swap etc.
This small PR approves the creation of popups.
---
> [Tech] Allow popups on MM portfolio page

- package.json
- src/frontend/ExtensionManager/index.module.scss
- src/frontend/ExtensionManager/index.tsx
- yarn.lock
> [Fix] ExtensionManager animation causing guestInstanceId errors

- src/backend/__mocks__/electron.ts
Mocks ipcMain.once to fix tests
---
> [Fix] Tests

- package.json
- src/frontend/App.tsx
- src/frontend/screens/MetaMaskHome/index.tsx
- src/frontend/screens/Onboarding/components/importOption/index.tsx
- src/frontend/screens/Onboarding/walletSelection/screens/import/index.tsx
- src/frontend/store/OnboardingStore.tsx
- yarn.lock
Import MetaMask with Recovery Phrase
1. Delete hyperplay appdata folder
2. Launch hyperplay
3. Connect with metamask extension
4. Click Import with Recovery Phrase
5. App refreshes several times, modal disappears, app navigates to the recovery phrase page in metmask home page
---
> [Feat] Import with Recovery Phrase

- package.json
> bump to 0.2.2

- package.json
- src/frontend/screens/Library/components/ContextMenu/index.tsx
- src/frontend/screens/Library/components/GameCard/index.tsx
- src/frontend/screens/Library/components/GamesList/index.tsx
- src/frontend/screens/Library/index.css
- src/frontend/screens/Settings/index.tsx
- yarn.lock
Updates the game card design
1. Plug in a controller and try to navigate the menu
2. Compare with figma designs https://www.figma.com/file/WS1FGyynDR0W3NEQouORPv/HyperPlay-Design-System?type=design&node-id=669-14252&t=DWAzJUaXopzQTgJg-4
3. Test each game card state and action
- Canceling a paused download is not working but this is the same behavior as on the ui overhaul branch. after merging down 0.2.2 into develop and ui overhaul we can restes/handle this on a separate branch
---
> [Feature] Update Game Cards

- LICENSE_ALL
- package.json
- src/backend/main.ts
- src/backend/metrics/types.ts
- src/frontend/components/UI/SearchBar/index.tsx
- src/frontend/components/UI/TopNavBar/index.tsx
> Release 0.3.0

- package.json
- src/backend/main.ts
- src/common/constants.ts
- src/frontend/index.tsx
- yarn.lock
> [Metrics] Add sentry crash reporting

- .github/workflows/build.yml
- .github/workflows/codecheck.yml
- .github/workflows/flatpak-build.yml
- .github/workflows/lint.yml
- .github/workflows/submodules-are-merged.yml
- .github/workflows/test-e2e-dev.yml
- .github/workflows/test-e2e-packaged.yml
- .github/workflows/test.yml
check that submodules are on main before merging to main
add concurrency check to jobs on branch to speed up development
disable e2e test gha's since they are broken
---
> [Tech] Submodule check

- package.json
> bump 0.4.0

- README.md
> [Fix] Add default chain for WC v2

- .github/workflows/release_flathub.yml
- flathub/update-flathub.ts
- package.json
- yarn.lock
run on release published trigger
copy release notes over
---
> [CI] Flathub Release ci/cd fixes

- src/backend/main_window.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
Fixes toggle of browser game fullscreen with F11
---
> [Fix] Browser game fullscreen toggle

- src/backend/storeManagers/hyperplay/games.ts
Fixes zip file extraction for games packaged as electron apps
---
> [Fix] Asar extraction

- README.md
Add steps to run the project locally
> chore: add local dev steps to readme

- README.md
We missed some extra text from the previous change on #456
> [FIX]: Remove extra text from README

- .github/workflows/build.yml
- yarn.lock
the windows gh runner frequently fails with the following during `yarn setup`
```
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: …
```
> [CI/CD] Fix Windows build

- src/backend/downloadmanager/utils.ts
Only send a game install success event if the install was successful
Send game install failed event if it fails
---
> [Metrics] Fix game install success and fail events

- package.json
> bump 0.6.0

- .github/workflows/submodules-are-merged.yml
Rename submodules job so it doesn't conflict with the lint job
---
> [CI] Rename submodules check job

- .github/workflows/release_windows.yml
- package.json
- yarn.lock
This sets a Windows release workflow that will be triggered with the others and automatically sends the binary to be signed on signpath and then gets back the artifacts and updates the latest.yml with the new information and creates or updates the release.
---
> [CI] Windows Release and Signing

- src/frontend/components/UI/Sidebar/index.scss
At some point, we lost our cursor: pointer for some of the sidebar links. This PR adds it back.
---
> [UI] Use cursor pointer for sidebar links

- src/backend/main.ts
- src/frontend/components/UI/Collapsible/Collapsible.tsx
- src/frontend/screens/Settings/sections/GamesSettings/index.tsx
closes https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/issues/543
---
> [Fix] Windows game settings showing wine/crossover

- public/locales/en/translation.json
- src/backend/main.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
- src/common/constants.ts
- src/common/utils.ts
- src/frontend/App.tsx
- src/frontend/ExtensionHandler/index.tsx
- src/frontend/ExtensionManager/index.tsx
- src/frontend/components/UI/AccountDropdown/index.tsx
- src/frontend/screens/MetaMaskPortfolio/index.tsx
- src/frontend/screens/WebView/index.tsx
This integrates the full page snaps store into hyperplay similar to how the portfolio or home page is integrated. Previously we were opening a separate window
This also fixes navigation to the MetaMask portfolio page from inside the MetaMask popup
Navigation to the snaps page from dropdown menu
Navigation to the snaps page from inside MetaMask popup
Navigation to the portfolio page from inside MetaMask  popup
---
> [UX] Improve snaps UX

- package.json
- yarn.lock
> [Chore] Bump 0.8.0

- src/backend/constants.ts
- src/frontend/components/UI/WebviewControls/index.tsx
- src/frontend/constants.ts
> refactor: update docs site url

- src/frontend/App.tsx
- src/frontend/components/UI/TopNavBar/index.tsx
- src/frontend/constants.ts
- src/frontend/screens/Library/components/LibraryTopBar/index.tsx
- src/frontend/screens/Login/index.tsx
Add feature flag for AGS. Disable it.
---
> Feature flag Amazon Game Store

- package.json
> [Chore] Bump 0.8.1

- src/backend/storeManagers/storeManagerCommon/games.ts
Fixes launching sideloaded browser games
---
> [Fix] Launch of sideloaded browser games

- package.json
- yarn.lock
Reverts HyperPlay-Gaming/hyperplay-desktop-client#629
> Revert "build(deps): bump axios from 0.26.1 to 1.6.0"

- package.json
> [Chore] Bump 0.9.0

- src/backend/storeManagers/gog/library.ts
closes #586 
Submodule PR: https://github.com/HyperPlay-Gaming/hyperplay-extension-helper/pull/35
Steps to test: 
- Go to store
- Open a community link (website, social, etc)
> [FIX]: open whitelisted webview content created in external browser

- src/frontend/components/UI/AccountDropdown/index.tsx
- src/frontend/screens/MetaMaskPortfolio/index.tsx
Enables Portfolio page for any connected wallet and fixes portfolio page for these wallets
---
> [Fix] Portfolio page for non mm extension wallets

- src/backend/api/misc.ts
- src/backend/main.ts
- src/common/constants.ts
- src/common/typedefs/ipcBridge.d.ts
**Steps to test**
- Connect wallet and email
- Launch a game
Right now you can check the status in the logs/terminal:
In case you have everything connected:
If you have something missing:
> feat(quest): mark hp quest as completed on game launch

- .github/workflows/submodules-are-merged.yml
Update achievements submodule to main after PR merge
Update gh workflow to prevent this from happening in the future similar to other submodules
---
> [Chore] Merge achievements submodule

- src/backend/storeManagers/storeManagerCommon/games.ts
- src/frontend/ViewManager.tsx
Update linux overlay
Details here: https://github.com/HyperPlay-Gaming/hyperplay-overlay/pull/6
> [Tech] Update linux overlay

- src/backend/api/misc.ts
- src/backend/protocol.ts
- src/common/constants.ts
- src/frontend/components/UI/AuthModal/index.tsx
How to test: https://app.qase.io/case/HC-144
---
> [TECH]: add support for oauth providers

- src/frontend/state/__tests__/libraryState.test.ts
> [CI] Fix Library State test

- src/frontend/components/UI/AccountDropdown/index.tsx
- src/frontend/components/UI/AuthModal/index.tsx
- hide the manage accounts button
- hide modal
---
> feat: hide auth login under feature flag

- package.json
Updating the version of package json to v0.11.0
---
> [RELEASE] v0.11.0

- package.json
- patches/@metamask+sdk+0.15.0.patch
- src/frontend/components/UI/AuthModal/index.tsx
- yarn.lock
Updates to `@metamask/sdk` 0.15.0 from 0.12.0
---
> [Chore] Update MetaMask SDK

- public/locales/en/translation.json
- public/locales/es/translation.json
- public/locales/uk/translation.json
- src/frontend/OverlayManager/index.tsx
- src/frontend/components/UI/Sidebar/components/SidebarLinks/index.css
- src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
> feat: add tooltips to sidebar and update copy of overlay text

- package.json
- src/common/typedefs/ipcBridge.d.ts
- yarn.lock
> [Fix] Trezor MetaMask Connection

- package.json
this release is not a hotfix. bumping minor
> bump 0.12.0

- src/backend/main.ts
> [Log] Remove duplicated log

- public/locales/uk/translation.json
Just a small fix to a wrong merge on weblate.
---
> [FIX] Weblate conflicts

- package.json
- yarn.lock
resolves https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/728 dependabot warning
---
> [Chore] Update Lavamoat

- package.json
- yarn.lock
Resolves https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/713
Dev server is snappier, bug fixes, and better build performance https://vitejs.dev/blog/announcing-vite5
Need to do some regression testing with the artifacts for this one
---
> [Chore] Update vite to v5

- src/common/types/electron_store.ts
**We need to https://github.com/HyperPlay-Gaming/hyperplay-extension-helper/pull/41 to be merged**
Currently, we're using the `isInitialized` flag from the [extension-helper store](https://github.com/HyperPlay-Gaming/hyperplay-extension-helper/blob/0dfa36a915a35947aef1eaec00cd110b1a4de632/ipcHandlers/index.ts#L325) to decide what we should show when users click the MM browser extension button in the [onboarding modal](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/blob/main/src/frontend/screens/Onboarding/walletSelection/index.tsx#L105).
The value is persisted in the default config file (`~/Library/Application Support/hyperplay/config.json`), but it is removed when the app is updated. I haven't figured out where yet, but the value of the config file is overwritten during the …
> fix: wallet intermittently resets and restarts onboarding

- src/backend/logger/__tests__/logfile.test.ts
Fix tests broke by the Logs PR
---
> [CHORE] Update getLogFile function in logfile.test.ts

- package.json
> [Chore] 0.13.0

- package.json
- vite.config.ts
- yarn.lock
Fixed path resolution on Vite.config.js file.
- Use the build from the PR on all Operating Systems and see if the app loads normally.
---
> [Fix] Fix White Screen on Windows build

- src/common/typedefs/ipcBridge.d.ts
submodule PR: https://github.com/HyperPlay-Gaming/hyperplay-proxy-server/pull/37
Needed for achievements and quests
> [Tech] add call or send method

- src/frontend/components/UI/SearchBar/index.tsx
Fix the current issue of failing to navigate to the game page from the search bar.
---
> [FIX] Search bar item click navigation

- yarn.lock
closes https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/847
> [Chore] Update json5 to 2.2.3

- src/backend/constants.ts
- src/backend/storeManagers/hyperplay/games.ts
Send the auth cookie with the license validate request
https://app.qase.io/project/HC?case=330&suite=43&previewMode=modal
---
> Send auth cookie with license validate request

- package.json
- src/backend/auth_provider_preload.ts
- fixes auth modal black background due to error during dev portal url constant import
---
> [Fix] Auth preload

- src/backend/__tests__/utils.test.ts
- src/backend/utils.ts
Fix launching native macOS games.
---
> [FIX] Native games launch on macOS

- package.json
- src/backend/storeManagers/storeManagerCommon/games.ts
- yarn.lock
Fix provider import causing MM extension to not display in browser games
> [Fix] Get connected provider

- src/frontend/components/UI/UpdateComponent/index.css
> [UI] Make loader bg transparent in library

- package.json
- yarn.lock
Fixes snap support for one of the proxy server endpoints
> [Fix] Snap support proxy server

- package.json
- src/backend/constants.ts
- src/backend/constants/folders.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
- src/backend/utils/hyperplay_api.ts
- src/backend/wine/runtimes/runtimes.ts
- yarn.lock
This one line fix for browser game metamask popup links turned into a larger change since the constants file import became a circular dependency.
To fix, the hpApi constants imports were moved into a separate folder.
> [Fix] browser game mm links

- src/backend/main.ts
Fix a regression after the move to Electron-Vite related with the webviewPreload file.
---
> [FIX] Epic Webview Login

- package.json
- yarn.lock
fixes a bug during trezor wallet connection to MM extension
> [Fix] Trezor connection window creation

- package.json
- src/backend/ipcHandlers/quests.ts
- src/common/types.ts
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
- src/frontend/helpers/getMidnightUTC.ts
- src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
- yarn.lock
Updates client to get quest from the dev portal and pass play streak eligibility to `QuestDetails` UI component
> [Quests] Update quest details UI 

- package.json
> [Chore] bump 0.15.2

- src/backend/api/questsAchievements.ts
- src/backend/ipcHandlers/achievements.ts
- src/common/typedefs/ipcBridge.d.ts
- src/common/types.ts
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/mintReward.ts
> [Feat] Add ERC721 and ERC1155 reward claiming

- src/frontend/components/UI/QuestsViewer/index.module.scss
- src/frontend/components/UI/QuestsViewer/index.tsx
- src/frontend/screens/Quests/index.module.scss
- src/frontend/screens/Quests/index.tsx
- yarn.lock
- if user is not logged in, show warning text on quests page and in the overlay above quests log/details
1. Log out
2. See the alert components in both the overlay and on the quests page
3. Log in
4. Alert disappears
quests page
overlay
> [Feat] add log in alert to quests page and overlay

- src/backend/ipcHandlers/quests.ts
- yarn.lock
- show test quests in dev and debug modes
> [Tech] get test quests in dev/debug modes

- package.json
- src/frontend/config.ts
- yarn.lock
This is a copy/paste of the code we have in the dev portal.
---
> feat: add all chains from @hyperplay/chains to wagmi config

- package.json
- yarn.lock
Brings in https://github.com/HyperPlay-Gaming/utils/pull/21
> [Fix] get streak days if > required and > 1 day old

- package.json
- public/locales/en/translation.json
- src/frontend/OverlayManager/Overlay/index.tsx
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/mintReward.ts
- yarn.lock
* Add a warning message when the connected wallet doesn't have enough gas to cover the transaction
* Add an error message when there is an error claiming the quest
* Balance check: https://app.qase.io/case/HC-352
* Claim error: https://app.qase.io/case/HC-353
---
> feat(quest):  add balance check and claim error CTA message 

- src/backend/ipcHandlers/launchdarkly.ts
- src/common/types.ts
- src/frontend/index.tsx
- yarn.lock
With the app version available in the context, we can target specific versions:
---
> feat: add app version to launch darkly context

- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/rewards/mintReward.ts
> fix(quest): remove amount formatting in claim params

- src/frontend/index.tsx
Added those info to the LD context so we can target these appVersions.
For instance:
---
> [TECH] Add AppVersion and language to LD context

- src/backend/metrics/types.ts
- src/frontend/OverlayManager/Overlay/index.tsx
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
- src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
- src/frontend/screens/Quests/index.tsx
- Add quest metrics
closes https://github.com/HyperPlay-Gaming/product-management/issues/502
> [Metrics] add quest metrics for screen, viewed, reward claim

- src/backend/main.ts
This should fix the edge case of users having the app opened for a long period of time without hitting the refresh button as well.
---
> [TECH] Check for HyperPlay games updates every hour

- package.json
> [Chore] Release 0.17.0

- src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
> fix(quest): show quest name as the quest card description

- yarn.lock
- fix long reward titles overflowing
> [Fix] long reward title

- src/backend/api/downloadmanager.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
How to test:
- Click a quest from a game you don't have in your library
- Click view game
---
> fix(quest): add game to library before navigating to game page

- src/frontend/index.tsx
> tech: add LD context log

- package.json
- src/backend/launcher.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/utils.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
- src/backend/utils/shouldOpenOverlay.ts
Fix overlay opening and play session tracking for epic forwarder listing games
> [Fix] open overlay for epic forwarder listings

- src/backend/launcher.ts
- yarn.lock
Regression introduced on #980.
Checklist to test:
---
> [FIX] Launching HP games on mac and linux

- .github/workflows/release_aur.yml
This Action was broken due to this issue with the AUR publish action:
https://github.com/KSXGitHub/github-actions-deploy-aur/issues/39
---
> [FIX] CI: AUR Publishing

- yarn.lock
`yarn upgrade` for each of the following
- jest
- fast-xml-parser
- electron builder
some general regression testing with the artifacts would be good since we updated the electron builder dependencies
> [Chore] Upgrade dependencies 

- package.json
- src/backend/api/questsAchievements.ts
- src/backend/launcher.ts
- src/backend/main.ts
- src/backend/utils/quests.ts
- src/backend/utils/shouldOpenOverlay.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
- src/frontend/helpers/getPlaystreakArgsFromQuestData.ts
- src/frontend/hooks/useSyncInterval.ts
- src/frontend/hooks/useTrackQuestViewed.ts
This PR syncs the play session every minute while playing a game.
closes https://github.com/HyperPlay-Gaming/product-management/issues/519
> [UX] sync playsession every minute

- src/common/typedefs/ipcBridge.d.ts
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
- src/frontend/hooks/useGetQuest.ts
- src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
- yarn.lock
- add search bar to quest summary table for searching quests on quest title or game title
> [Feat] add search bar to quest summary table

- src/backend/storeManagers/hyperplay/games.ts
- src/common/constants.ts
- src/frontend/helpers/library.ts
> [Tech] Remove references to valistBaseApiUrlv1

- public/locales/en/translation.json
- src/frontend/components/UI/QuestsViewer/components/QuestLogWrapper/index.tsx
Update popover text for g7 credits
> [UI] fix total claimed g7 credits text

- src/frontend/OverlayManager/Overlay/index.tsx
Fixes extension showing if connection method changes after overlay is launched
closes https://github.com/HyperPlay-Gaming/product-management/issues/524
https://app.qase.io/project/HC?case=355&suite=5
https://app.qase.io/project/HC?case=354&suite=5
> [Fix] should show extension

- src/frontend/state/GameUpdateState.ts
fix Epic/gog manual game updates for those who opted out of automatic updates
> [Fix] epic/gog manual updates

- package.json
- src/backend/utils/shouldOpenOverlay.ts
- yarn.lock
We had a regression on https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/998 for launching the overlay for epic forwarder listings.
> [Fix] regression on launching overlay for epic forwarder listings 

- src/backend/api/library.ts
- src/backend/downloadmanager/utils.ts
- src/backend/ipcHandlers/mods.ts
- src/backend/services/ExtractZipService.ts
- src/backend/storeManagers/hyperplay/games.ts
- src/backend/storeManagers/hyperplay/utils.ts
- src/common/typedefs/ipcBridge.d.ts
- src/common/types.ts
- src/frontend/helpers/library.ts
- src/frontend/screens/Library/components/InstallModal/ModDialog/index.tsx
This PR
- moves `prepareBaseGameForModding` to the backend install function
- sets CWD for client patcher spawn
> [Fix] mod backend

- package.json
- src/backend/main.ts
> [Tech] update playsession

- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
fix the race condition of the wallet balance check after switching account.
This PR fixes a bug related to the `useBalance` hook when switching chains. The issue was that after `switchChainAsync` resolved, the balance was not updated to reflect the current chain's balance. This caused an incorrect balance check when a user switched to the quest's network, potentially allowing a signature to be granted even if the user didn't have enough gas on the new chain.
To resolve this, the balance is now fetched directly using the [`getBalance`](https://wagmi.sh/core/api/actions/getBalance#chainid) function from the WAGMI API, ensuring that the balance reflects the correct chain immediately after switching, without waiting for WAGMI to fully update the chain configuration in the hooks.
1. Find a …
> fix(quest-claim): balance check race condition

- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
We were try-catching the errors in the claim functions. We need to let the functions throw so they can be caught by the mutation. It will handle it and store the value in `mutation.error`.
```ts
if (writeContractError || claimRewardsMutation.error || switchChainError) {
// show UI error
}
```
---
> feat(quest-claim): show error ui for claim errors

- .github/workflows/build-mac-arm64.yml
- .github/workflows/build.yml
- .github/workflows/codecheck.yml
- .github/workflows/flatpak-build.yml
- .github/workflows/lint.yml
- .github/workflows/release_flathub.yml
- .github/workflows/release_linux.yml
- .github/workflows/release_macOS.yml
- .github/workflows/release_snap.yml
- .github/workflows/release_windows.yml
- .github/workflows/test-e2e-dev.yml
- .github/workflows/test-e2e-packaged.yml
- .github/workflows/test.yml
- Upgraded all Workflows to the current NodeJS Stable release.
- Upgraded `actions/checkout` to v4
- Removed recursive submodules param since it is not needed anymore
---
> [CI]: Workflow maintenance

- src/backend/utils/quests.ts
Improve logs when POST'ing playsession
> [Tech] improve playsession POST logs

- public/locales/en/translation.json
- src/frontend/components/UI/QuestsViewer/components/QuestDetailsWrapper/index.tsx
- src/frontend/hooks/useGetG7UserCredits.ts
> feat(quest): add warning if g7 account is not detected on external task claim

- package.json
> chore: bump package for release

- package.json
- src/frontend/OverlayManager/Overlay/index.module.scss
> fix(overlay): set overlay content height to 100%

- package.json
- patches/@metamask+sdk+0.29.0.patch
- src/backend/storeManagers/hyperplay/utils.ts
- src/frontend/screens/Onboarding/walletSelection/screens/scan/index.tsx
- src/frontend/screens/WebView/index.tsx
- yarn.lock
Upgrade mm sdk to latest release
> [Tech] upgrade mm sdk

- yarn.lock
closes https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/1101 with `yarn update vite`
> [Tech] update vite

- package.json
- yarn.lock
closes https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/1067
> [Tech] update express

- src/backend/logger/logger.ts
- src/backend/metrics/types.ts
- src/backend/updater.ts
Add some new events for the auto update and more logs to try to track down more edge cases.
---
> [TECH] Track AutoUpdate issues

- src/frontend/OverlayManager/Overlay/index.tsx
> [Fix] overlay nav bar link alert number

- yarn.lock
handles https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/1121
closes https://github.com/HyperPlay-Gaming/product-management/issues/696
> [Chore] Update secp256k1

- package.json
- yarn.lock
closes https://github.com/HyperPlay-Gaming/product-management/issues/699
> [Fix] bump extension-provider

- package.json
- src/frontend/screens/Library/components/InstallModal/ModDialog/constants.ts
- src/frontend/screens/Library/components/InstallModal/ModDialog/index.tsx
Will use a flag from LD now instead of hardcoding it.
---
> [FIX] ChromieCraft download link

- .gitignore
- package.json
- yarn.lock
bump `@hyperplay/providers` package
> [Chore] bump providers

- package.json
- public/locales/en/translation.json
- src/frontend/screens/Library/components/InstallModal/ModDialog/index.tsx
> [Chore] Update Market Wars copy

- package.json
> [Chore] bump 0.22.0

- .github/workflows/build.yml
- .github/workflows/flatpak-build.yml
Also added error handling and compression options to a lower level than default due to the size of artifacts.
Context:
---
> [CI] Update upload-artifact action to v4

- src/backend/main.ts
only await on handle to keep quests-ui in sync. if `syncPlaySession` fails in `'launch'`, still send Game Closed event
> [Tech] await sync playsession only on handle

- src/frontend/screens/Onboarding/index.module.scss
> [UI] Update welcome modal to be responsive

- src/backend/metrics/types.ts
- src/frontend/OverlayManager/Overlay/NavBarOverlayWrapper/index.tsx
- src/frontend/components/UI/AccountDropdown/index.tsx
- src/frontend/screens/MetaMaskPortfolio/index.tsx
closes https://github.com/HyperPlay-Gaming/product-management/issues/745
> [Metrics] improve overlay, portfolio, and marketplace metrics

- src/frontend/screens/Settings/components/SettingsModal/index.tsx
- src/frontend/screens/Settings/index.tsx
- src/frontend/screens/Settings/sections/GamesSettings/index.scss
- src/frontend/screens/Settings/sections/GamesSettings/index.tsx
Replaced Collapsible elements for Tabs to follow the Settings screen design and also make it more practical. 
---
> [UI] Refactor GamesSettings component to Tabs instead of Collapsible

- .github/workflows/build.yml
- package.json
- pnpm-lock.yaml
closes https://github.com/HyperPlay-Gaming/product-management/issues/824
> [Fix] MetaMask stuck loading

- buildResetExtension.js
Fix reset extension 
closes https://github.com/HyperPlay-Gaming/product-management/issues/836
> [Fix] Reset extension

- src/frontend/components/UI/Sidebar/components/SidebarLinks/index.css
- src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
- src/frontend/components/UI/Sidebar/index.scss
<--- Description --->
Replaced the old Twitter icon with the X logo
---
> UI]replace twitter icon with x icon

- package.json
- src/frontend/ExtensionManager/components/ExtensionContents/index.tsx
- src/frontend/screens/MetaMaskHome/index.tsx
- src/frontend/screens/MetaMaskPortfolio/index.tsx
closes https://github.com/HyperPlay-Gaming/product-management/issues/764
https://app.qase.io/case/HC-530
- note that the expected behavior for step 7 is failing on main
> [Fix] MetaMask extension notification window sometimes not showing in overlay

- .github/workflows/release_macOS.yml
- electron-builder.yml
- package.json
install missing setuptools package.
---
> [CI] Fix macOS Arm64 Release workflow

- src/backend/launcher.ts
This fixes launching of HyperPlay or sideloaded games when offline
closes https://github.com/HyperPlay-Gaming/PX-PM/issues/23
https://app.qase.io/case/HC-543
> [Fix] Sideloaded game launch if offline

- package.json
- pnpm-lock.yaml
- src/backend/ipcHandlers/quests.ts
- src/frontend/screens/Quests/index.tsx
brings in https://github.com/HyperPlay-Gaming/hyperplay-ui/pull/443
closes https://github.com/HyperPlay-Gaming/px-pm/issues/37
> [Feat] Remove quest table sort, get quests by start date newest first

- package.json
- pnpm-lock.yaml
> chore: bump quest-ui version

- src/frontend/screens/Quests/index.tsx
This PR is to add fuzzy search to the client.  It was implemented only in the store and generated bugs because of conflicts of different search logic.
- Test if the search for the **_game name_** matches what is shown and suggested;
- Test if the search for the **_quest name_** matches what is shown and suggested.
---
> [Feat] implemented Fuse.js to search by quest name and game title.

- package.json
> [Fix] rm product name

- package.json
- pnpm-lock.yaml
> fix: bump quest-ui version to fix alert styles

- package.json
- src/backend/main.ts
Fixes auto-update for new installs on current version
> [Fix] Auto-update

- src/frontend/screens/Quests/index.tsx
Handle search param on navigate to quests page correctly
> [Fix] pass search param to redirect correctly

- package.json
- pnpm-lock.yaml
Update proxy server to handle bytes32 array params
closes https://github.com/HyperPlay-Gaming/px-pm/issues/345
> [Chore] update proxy server

- package.json
- pnpm-lock.yaml
- src/backend/proxy/ipcHandlers.ts
- Add FF to switch MMM connection under the hood
- Update `@metamask/sdk` in providers
closes https://github.com/HyperPlay-Gaming/px-pm/issues/332
> [Tech] Improve MetaMask Mobile connection

- package.json
- pnpm-lock.yaml
closes https://github.com/HyperPlay-Gaming/dx-pm/issues/148
Run the active wallet test run https://app.qase.io/plan/HC/9 and make sure these events are added to MixPanel. You can trigger an event error by rejecting the signature.
- Update Active Wallet Start
- Update Active Wallet Success
- Update Active Wallet Error
- Add Gameplay Wallet Start
- Add Gameplay Wallet Success
- Add Gameplay Wallet Error
If you run in dev mode this branch, the events will show up here https://mixpanel.com/project/2935160/view/3459800/app/events
---
> feat(active-wallet): add events tracking

- package.json
- pnpm-lock.yaml
brings in https://github.com/HyperPlay-Gaming/quests-ui/pull/88
closes https://github.com/HyperPlay-Gaming/px-pm/issues/306
I updated this expects on the last step of this test for this https://app.qase.io/case/HC-377
> [Fix] Claim btn invalidate on claim

- src/frontend/screens/Quests/index.tsx
closes https://github.com/HyperPlay-Gaming/px-pm/issues/326
> [UI] Remove close button on not logged in quest banner

- package.json
- pnpm-lock.yaml
Brings in https://github.com/HyperPlay-Gaming/hyperplay-ui/pull/511
closes https://github.com/HyperPlay-Gaming/px-pm/issues/328
on hover now
> [UI] fix set active wallet button hover

- package.json
- pnpm-lock.yaml
- rm discord link for certain error messages
- update alert info UI for wallet connected alerts
> [Chore] bump quests-ui

- .github/workflows/build-mac-x64.yml
- .github/workflows/build.yml
- .github/workflows/flatpak-build.yml
- .github/workflows/release_linux.yml
- .github/workflows/release_macOS.yml
- .github/workflows/release_snap.yml
- .github/workflows/release_windows.yml
- electron-builder.yml
- package.json
- patches/electron-vite.patch
- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/backend/ipcHandlers/achievements.ts
- vite.config.ts
Update ext provider
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/356
https://app.qase.io/case/HC-585
> [Tech] update extension provider

- src/backend/config.ts
- src/backend/constants.ts
- src/backend/launcher.ts
- src/backend/utils.ts
- src/backend/utils/compatibility_layers.ts
- src/frontend/screens/Settings/components/TraySettings.tsx
- src/frontend/screens/WineManager/index.tsx
This reverts commit 5d24c2d49d10ae9746034ac8e412d3574e41afc5.
---
> Revert "[Feat] Add better Compatibility layer support for Intel Macs (#1253)"

- package.json
- pnpm-lock.yaml
- src/frontend/components/UI/QuestDetails/index.tsx
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/570
Updated this test https://app.qase.io/case/HC-587
> [Feat] Add watch asset call to erc20's on successful claim

- package.json
- pnpm-lock.yaml
> fix(quest): do correct eligibility invalidation post claim

- package.json
- pnpm-lock.yaml
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/584
https://app.qase.io/case/HC-592
https://app.qase.io/case/HC-593
https://app.qase.io/case/HC-594
> [Fix] Okx, trust wallet & bybit quest reward claim flow

- package.json
- pnpm-lock.yaml
- src/frontend/components/UI/DownloadToastManager/index.tsx
- src/frontend/components/UI/QuestRewardClaimedToast/index.tsx
React-draggable needs to be updated with react 19 and we no longer need this feature, so let's remove to reduce maintenance costs in the future.
> [Fix] Remove draggable

- package.json
- src/frontend/screens/Game/GamePicture/index.tsx
- src/frontend/screens/Library/components/GameCard/index.tsx
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/648
> [Fix] game card fallback image

- package.json
- pnpm-lock.yaml
- public/locales/en/gamepage.json
- src/frontend/components/UI/DownloadToastManager/index.tsx
Update DownloadToast based on the talk here: https://github.com/HyperPlay-Gaming/hyperplay-ui/pull/521
Closes: https://github.com/orgs/HyperPlay-Gaming/projects/16/views/8?pane=issue&itemId=114464159&issue=HyperPlay-Gaming%7Chyperplay-pm%7C597
---
> Feat/add new download toast UI changes
