- src/common/typedefs/ipcBridge.d.ts
- src/common/types.ts
- src/frontend/ExtensionHandler/index.tsx
Adds deprecated send and sendAsync provider methods necessary for some games to run like Defi Kingdoms.
Tests are failing due to electron and other module mocks failing. This should be addressed on a separate branch.
---
> [Tech] Add old provider methods

- src/frontend/screens/Onboarding/walletSelection/screens/import/index.tsx
Fixes an issue of the application crashing when trying to install the MetaMask extension.
---
> [Fix] import mm crash

- src/frontend/ExtensionManager/index.module.scss
- src/frontend/ExtensionManager/index.tsx
- src/frontend/components/UI/Sidebar/index.tsx
- src/frontend/store/ExtensionStore.ts
* feat: clicking outside of popup closes the popup(if the clicked element isn't a webview)
* fix: 2 popups showing up at the same time
* fix: popup menuitem temporarily doesn't react to clicks
* fix: popup menuitem at times doesn't show whether the popup is open or not
A small store has been introduced that manages the popup open state, and arranges the communication between the sidebar & ExtensionManager. Having a single source of truth reduced complications and clarifies the logic as opposed to having this communication run through the backend.
---
> feat: overhauled & animated extension popup and notification

- src/backend/api/library.ts
- src/backend/electron_store.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/frontend/state/GlobalState.tsx
Watches library changes from the backend and pushes those to the GlobalState.
This is a fix for the need to refresh the entire library when adding a HP game, and making that process instant.
---
> [Tech] Watch library changes and commit them to GlobalState

- public/locales/en/gamepage.json
- src/backend/storeManagers/gog/games.ts
- src/backend/storeManagers/gog/library.ts
- src/backend/storeManagers/legendary/games.ts
- src/frontend/helpers/library.ts
Import directory is necessary for single file applications on mac so this reverts the previous change to import executable
---
> [Fix] Import Folder

- src/backend/providerStore.ts
- src/common/typedefs/ipcBridge.d.ts
- src/common/types.ts
- src/common/types/electron_store.ts
- src/frontend/screens/Onboarding/walletSelection/index.tsx
- src/frontend/store/OnboardingStore.tsx
- src/frontend/store/storage/providerStore.ts
Removes frontend electron store from branch. 
This is important because it is a security concern, requires duplicate store definitions, prevents us from setting nodeIntegration: false in the preload script, and is overly complicated. The backend should abstract this away from the frontend.
This also removes Web3ProviderTypes and uses PROVIDERS which is already used by the proxy server.
---
> [Refactor] Default Wallet

- src/frontend/ExtensionManager/index.tsx
This reloads MetaMask popup and notification windows on open for the main client renderer process.
This fixes the issue where you have to log into MetaMask twice (on the notification and then the popup screen).
---
> [Fix] Reload MetaMask on Open

- src/frontend/ExtensionHandler/index.tsx
When in devmode, the application is substantially slower with reloads, therefor this issue is only present in production builds.
Initial issue:
1. launch packaged version of HyperPlay
2. Import extension wallet
3. eth_requestAccounts doesn't get called properly, the wallet doesn't connect
In the above scenario, the MetaMask extension wasn't available yet to accept requests, thus this branch checks whether the connection has already been established, and if not, waits until it has been.
---
> [Fix] Fix eth_requestAccounts not executing after reloadApp event

- src/backend/storeManagers/sideload/games.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
Browser games with links that open new windows to different parts of their game now have the HyperPlay overlay available
Browser game windows default to fullscreen now
1. Open defi kingdoms
2. Click Articles on the bulletin board. This does not open in full screen or with the overlay since domain (`medium.com`) does not match `defikingdoms.com`
3. Click on Tutorials on the bulletin board. This window has the same domain name `defikingdoms.com` so overlay is injected. If you click start playing, `game.defikingoms.com` will open in a new window which also has the overlay since the domains match
If you exit out of the bulletin board, you can get it back by clicking in the top right menu button, then click Bulletin Board at the top.
Bulletin board with test actions identified with the red pen …
> [Feat] Open browser game links with overlay, Make fullscreen

- src/backend/storeManagers/hyperplay/games.ts
Adds `<developer name> - ` prefix to game folder
Fixes issue where games with a single apostrophe in `platformInfo.name` or `gameInfo.title` would not extract on windows
---
> [Fix] Unzip Windows

- src/backend/storeManagers/hyperplay/games.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
Fixes:
- uninstall folder name
- gameInfo version was not updating on refresh so updated games would always have the old version on install info
- ENOENT error when launching a game with an exe override for an exe that does not exist
To Test:
1. add another world to library
2. change library.json gameInfo.install.version to 0.1.21
3. refresh
4. game should be shown as updateable
5. update game
6. launch game
---
> [Fix] HyperPlay Store Manager

- src/backend/storeManagers/hyperplay/games.ts
- src/backend/storeManagers/hyperplay/library.ts
Fixes
1. Uninstalled games auto updating
2. Delisted store games preventing `listUpdateableGames` from working
3. Recursive folder structure during updates
---
> [Fix] HP Store Manager

- src/backend/__mocks__/electron.ts
- src/backend/__mocks__/providerCallbacks.ts
Struct params passed are passed from web3.unreal as strings. This PR parses these strings if the corresponding ABI type is a tuple.
To test, run this curl command in a bash terminal while hyperplay is running
```
curl --location --request POST "localhost:9680/sendContract" \
--header 'Content-Type: application/json' \
--data-raw '{
"contractAddress": "0x2e0cb17ed5f24bfcbb30d61e195d90e06e388e1e",
"functionName": "setWeapon",
"params": ["1","[\"rifle\", \"2\", \"4\", \"3\"]"],
"valueInWei": "0",
"chain": {
"chainId": "5"
}
}'
```
---
> [Proxy] Support Struct Params

- package.json
- src/backend/utils.ts
Noticed this small bug after merging the PR.
With the current filter it won't find anything on macOS since it will try to find Wine-GE for it but it does not exists.
---
> [FIX] Auto Download Wine on macOS

- src/backend/__tests__/utils.test.ts
- src/backend/api/misc.ts
- src/backend/hyperplay_store_preload.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/backend/storeManagers/hyperplay/utils.ts
- src/backend/storeManagers/index.ts
- src/backend/storeManagers/legendary/library.ts
- src/backend/utils.ts
- src/common/typedefs/ipcBridge.d.ts
- src/common/types.ts
- src/frontend/App.tsx
- src/frontend/StoreNavHandler/index.tsx
For games with 
```
launch_epic?: boolean
epic_game_url?: string
```
defined, this [store PR](https://github.com/HyperPlay-Gaming/hyperplay-store/pull/11) will show the game page action button as "Play in Epic Store" and after clicking it, the user will be navigated to the corresponding listing in the Epic Store.
When the game is added and getGameInfo is called for the epic game, a map (generated on client start) will merge the HyperPlay listing `GameInfo` metadata with the legendary metadata. This way we can still show web3/HyperPlay specific metadata like token requirements even though the game is managed by legendary
To test, you will need to 
1. replace the developers.hyperplay.api/listings axios calls with a test.json that you import.
2. manually change one of the game's metadata to …
> Support HyperPlay Store Games Hosted on Epic

- src/backend/downloadmanager/utils.ts
- src/backend/storeManagers/hyperplay/games.ts
- src/backend/utils.ts
- src/common/types.ts
- src/frontend/hooks/constants.ts
- src/frontend/screens/Accessibility/index.css
- src/frontend/screens/Game/GamePage/index.tsx
- src/frontend/screens/Library/components/GameCard/constants.ts
- src/frontend/state/GlobalState.tsx
EasyDL downloads chunks in parallel so connections cannot equal 1 without losing the pause feature and forcing the download into a single chunk 
also includes a small css fix to settings
---
> [Fix] Hotfix

- src/backend/storeManagers/hyperplay/library.ts
- src/backend/utils.ts
This fixes an issue with `the wake prealpha` failing to download
---
> [Fix] Handle Invalid Download Urls

- public/locales/en/gamepage.json
- public/locales/en/login.json
- public/locales/en/translation.json
- src/backend/api/misc.ts
- src/backend/utils.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/screens/Onboarding/walletSelection/index.module.scss
- src/frontend/screens/Onboarding/walletSelection/screens/scan/index.tsx
This allows the user to use wallet connect with wallets that cannot parse out the base uri from the metamask deep link qr code
To test Ledger Live for example
1. Go to accounts
2. click on an account
3. click wallet connect icon in top right
4. paste URL you copied with the copy base uri button
wallet connect has base uri button
mm mobile does not have the base uri button
---
> [Feature] Add copy base uri button

- src/frontend/components/UI/Dialog/index.css
- src/frontend/components/UI/StopInstallationModal/index.tsx
- src/frontend/screens/DownloadManager/components/ProgressHeader/index.tsx
- src/frontend/screens/Library/components/GameCard/index.tsx
- src/frontend/screens/Library/index.tsx
Some Fixes to the PR #346:
- Show only the filters for the stores you are logged in to.
- Set 'Keep files' to false by default when canceling a install.
- Do not show Zero progress when changing screens.
- Alternative fix to the empty card on library when a dialog is show.
---
> [FIX] Some fixes for #346

- src/backend/downloadmanager/utils.ts
- src/backend/launcher.ts
- src/backend/main.ts
- src/backend/metrics/metrics.ts
- src/backend/metrics/types.ts
- src/backend/storeManagers/gog/games.ts
- src/backend/storeManagers/gog/library.ts
- src/backend/storeManagers/legendary/games.ts
- src/backend/storeManagers/legendary/library.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
- src/backend/utils.ts
- yarn.lock
adds game_title to install, update, and uninstall events
adds game launched and game closed events. the game closed event reports playtime as well
for gogdl, hp, sideload runners, this tracks the child process 
for legendary this tracks the process of the pid outputted to stdout when launching a game
if a game exe launches a separate process then closes, the playtime reported will be < actual playtime
- we could inject on process name but it would be nice to not require the dev to provide this and for the games I tested, the above approach was working well
this works for browser and native games as well. it also reports the platform installed as this might be different that os and is useful for game devs
Games tested:
- Defi kingdoms (hp browser)
- Kosium (hp native)
- dragon's dogma …
> [Metrics] Add game launch and closed events, add game_title

- src/frontend/components/UI/Dialog/components/Dialog.tsx
- src/frontend/components/UI/Dialog/index.css
Fixes empty game card sized div when uninstall modal is shown
---
> [Fix] Uninstall games list layout shift

- public/locales/en/translation.json
- src/frontend/browserGame/BrowserExtensionManager/index.tsx
Change X icon to "Exit Game" in browser game overlay
---
> [UI] Change X icon to "Exit Game" in browser game overlay

- src/frontend/screens/Library/components/InstallModal/SideloadDialog/Warning/index.tsx
- src/frontend/screens/Library/components/InstallModal/index.tsx
Fix the platform selection when sideloading a game.
I thought this was fixed already but I was mistaken.
---
> [FIX] Platform selection on Add Game screen

- src/backend/storeManagers/hyperplay/games.ts
fixes hp game manager `isNative` returning false for native linux games due to 'Linux' === 'linux' returning false
Tested with Kosium (the only hp game with a linux native build) on linux
---
> [Fix] Launching of native linux games

- src/backend/main_window.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
- src/frontend/OverlayManager/index.tsx
toggles fullscreen in browser games with F11 hotkey like regular browsers
---
> [Feat] Browser game fullscreen hotkey

- src/backend/main_window.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/screens/Onboarding/components/importOption/index.module.scss
- src/frontend/screens/Onboarding/components/importOption/index.tsx
- src/frontend/screens/Onboarding/index.module.scss
- src/frontend/screens/Onboarding/walletSelection/screens/import/index.module.scss
- src/frontend/screens/Onboarding/walletSelection/screens/import/index.tsx
Import MetaMask from automatically detected chromium based browser profiles or from a manual path if the browser is installed in a custom path or for an unsupported browser based on chromium 
- Linux
- Windows
- Mac
---
> [Feat] Import MetaMask from profiles

- .github/workflows/release_flathub.yml
- .gitignore
- README.md
- flathub/update-flathub.ts
- package.json
- yarn.lock
automatically generate flathub PR on release tag
Known issues:
- the build will have to be re-run in buildbot.flathub.org after the release is published since it uses the release tar.xz download url and cannot access it if the release is still in draft
- the sha512 hash calculated was not able to be tested and compared for equality between electron builder and the tar xz built in this gha. if the build fails, check this as well
---
> [CI] Automate Flathub Releases

- src/backend/main.ts
Metrics fail on initial opt in due to sentry init throwing from being called after app.whenReady() 
This removes the failing sentry init. This also means we won't get error logs on initial launch if the user opts in to metrics. We should consider an upstream PR to https://github.com/getsentry/sentry-electron to add an enable/disable toggle to sentry after init is called 
error message: 
```
Error occurred in handler for 'changeMetricsOptInStatus': SentryError: Sentry SDK should be initialized before the Electron app 'ready' event is fired
```
---
> [Fix] Sentry init after ready

- src/backend/constants.ts
- src/backend/downloadmanager/utils.ts
- src/backend/storeManagers/hyperplay/games.ts
- src/common/types.ts
- src/frontend/helpers/library.ts
- src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
- src/frontend/screens/Library/components/InstallModal/index.tsx
Access code gate games on install
Stores access code locally in `gameInfo.accessCodesCache` for use during update
UI uses the existing text input field in the app. I think we should update the install modal designs to latest design on a separate branch
here are some access codes to test the Kosium Beta channel with 
H87YS0VDATNM
6915SC7P4UGY
0I0EJBVJI865
KFDC8T9RKT0H
WW6YGNBCUE9H
M2SSQMZFMO8E
J1W0871M1B9D
IAW4NTI2LBFA
OPBCBE50I1GB
2EJ2XQ0COTRN
---
> [Feature] Access codes

- src/backend/utils.ts
an already formed url doesn't need encodeURI
this can cause issues for certain urls which then throws a "can't get headers" error
for instance
```
const a = encodeURI('https://gateway.valist.io/ipfs/bafybeia4d6wvhmmokscxubsxf4xjswzh4yqdotnk7ozutzymabq5rm2f24/windows_amd64/Thetan%2BLauncher%2BSetup%2B1.0.5.zip')
console.log(a)
//ouputs: "https://gateway.valist.io/ipfs/bafybeia4d6wvhmmokscxubsxf4xjswzh4yqdotnk7ozutzymabq5rm2f24/windows_amd64/Thetan%252BLauncher%252BSetup%252B1.0.5.zip"
//ERROR! not the same as a
```
---
> [Fix] rm encodeUri of already formed url

- .github/workflows/build.yml
- .github/workflows/codecheck.yml
- .github/workflows/flatpak-build.yml
- .github/workflows/lint.yml
- .github/workflows/release_flathub.yml
- .github/workflows/release_linux.yml
- .github/workflows/release_macOS.yml
- .github/workflows/test-e2e-dev.yml
- .github/workflows/test-e2e-packaged.yml
- .github/workflows/test.yml
- .gitignore
- .yarnrc
- .yarnrc.yml
- package.json
- yarn.lock
see https://github.com/LavaMoat/LavaMoat/tree/main/packages/allow-scripts for more info on the package
Basically we disable all the npm package lifecycle scripts by default and only allow the ones listed in the package.json through.
Instead of installing dependencies with `yarn` or `yarn install`, we will now have to use `yarn setup` or the allowed package lifecycle scripts will not be executed
The fortawesome packages just log their license in the postinstall script so these can be disabled
@lavamoat/preinstall-always-fail is a package that just throws on preinstall to check that we are ignoring scripts correctly
`discord-rich-presence-typescript>discord-rpc>register-scheme` is not necessary since it can import electron
- see https://github.com/discordjs/RPC/blob/9e7de2a6d917591f10a66389e …
> [Tech] Add LavaMoat allow scripts

- src/backend/metrics/metrics.ts
- src/backend/metrics/types.ts
Checks that an opted in user has a unique metrics id on app launch
Reports a 'Metrics Error Correction' event if the user is opted in but still has the anonymous id so that we will know how many people were affected historically
---
> [Metrics] Ensure unique metrics id on launch

- src/backend/storeManagers/hyperplay/electronStore.ts
In the case there are two duplicate game infos locally (one with the old id and one with the new id), this will remove the old game info
---
> [Fix] Remove duplicate game infos

- src/frontend/App.tsx
Here's a good explanation of the current behavior https://www.loom.com/share/b76e1dac916242788a2e81fa51df0a01 please watch first
By using different React keys, we can ensure that the webview is unmounted on navigation. See https://www.makeuseof.com/react-keys-avoid-component-conflict/
**The caveats with this approach are two, both cause by the webview being unmounted:**
1. The history is lost between navigation. If you go from one route that uses webview to another, you cannot use the webview's navigation go back arrow to go to the previous page.
2. Going to a different route makes the compontent to reload the page even if it has visited before. In the current implementation because the webview component is never unmounted, it seems the webview caches the urls.
> refactor(webview): use keys in webview components routes

- src/backend/storeManagers/storeManagerCommon/games.ts
Some browser games are having their keyboard input blocked due to these missing brackets
---
> [Fix] Browser Game Keyboard Input

- src/frontend/components/UI/ChannelNameSelection/index.tsx
- src/frontend/screens/Library/components/InstallModal/index.tsx
Previously access code input would only show when there was >1 channel available.
For games that are only gating main, this would cause the access code text input field to be hidden
---
> [Fix] Main access codes

- src/backend/storeManagers/hyperplay/games.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/backend/storeManagers/hyperplay/utils.ts
- yarn.lock
Games that have spaces or uppercase letters will always show as needing an update under the current logic
The lower casing and whitespace removal is for backwards compatibility for games installed with clients <0.5.0, but this was not being done on install for new games.
The only game currently affected is Moonblasters
---
> [Fix] Games with spaces in version name are always updateable

- public/locales/en/translation.json
- src/backend/__tests__/utils.test.ts
- src/backend/config.ts
- src/backend/launcher.ts
- src/backend/main.ts
- src/backend/storeManagers/gog/games.ts
- src/backend/storeManagers/legendary/games.ts
- src/backend/storeManagers/storeManagerCommon/games.ts
- src/backend/tools.ts
- src/backend/utils.ts
- src/backend/utils/__tests__/compatibility_layers.test.ts
- src/backend/utils/compatibility_layers.ts
- src/common/types.ts
- src/frontend/screens/Settings/components/AutoDXVK.tsx
- src/frontend/screens/Settings/components/AutoVKD3D.tsx
- src/frontend/screens/Settings/components/EnableDXVKFpsLimit.tsx
- src/frontend/screens/Settings/components/ShowFPS.tsx
- src/frontend/screens/Settings/sections/GamesSettings/index.tsx
With this, Hyperplay will look for a current setup of the apple's GPTK and list it under the Wine List
- To download the build to test, go bellow under 'CHECKS' and build_macOS click on `details`. Then on the page that will open, click on SUMMARY. And then go to ARTIFACTS and download the build for your system.
- Since this build is NOT signed (only releases are), you need to first run this command on the terminal: `xattr -d -r com.apple.quarantine PATH_TO/HyperPlay.app`
- Make sure you have installed the gaming porting toolkit following the Install instructions provided by Apple.
- Make sure Spotlight is enabled and the command `mdfind wine64` returns something on the terminal.
- Try to run some games and make sure it is working already.
- When opening HyperPlay, go to Settings and on …
> [macOS - Feat] Add support for Apple Gaming porting toolkit

- src/backend/__tests__/utils.test.ts
This utils test sometimes fails due to small delays between when
`const lastProgressTime = Date.now().valueOf() - 1000 * 4` 
is called in the test and when 
`const elapsedSeconds = (Date.now() - lastProgressTime) / 1000`
is called in `calculateEta`
We should just accept 04 or 05 to pass the test
---
> [CI] Fix utils test rounding error

- public/locales/en/gamepage.json
- public/locales/en/translation.json
- src/backend/api/library.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/screens/Library/components/GameCard/index.tsx
Right click an uninstalled HyperPlay game card and click "Remove" to remove it from your library json file
---
> [Feat] Add remove from library option to game card

- src/frontend/ExtensionManager/index.module.scss
- src/frontend/components/UI/TopNavBar/index.module.scss
- src/frontend/index.scss
Before, scrolling would hide the MetaMask popup and notification windows on the library.
With this PR, it now stays fixed
---
> [UI] Update metamask container to be position fixed

- src/backend/game_config.ts
- src/backend/launcher.ts
- src/frontend/screens/Settings/components/SteamRuntime.tsx
These changes enable Steam Runtime by default when using Proton on Linux, without it, on builds that are not-flatpak links inside games won't open a browser.
More details on #469
---
> [FIX] Open game links when using proton on linux

- src/frontend/ExtensionManager/index.tsx
Allows mm popup and notification windows to open external windows. Necessary to open snaps page
---
> [Fix] MetaMask snaps external link

- .husky/post-checkout
- .husky/post-merge
Since adding lavamoat allow scripts, we now need to run `yarn setup` instead of `yarn`
Husky commands were never updated
---
> [Tech] Update husky commands

- src/backend/api/misc.ts
- src/backend/constants.ts
- src/backend/main.ts
- src/common/typedefs/ipcBridge.d.ts
- src/common/types/electron_store.ts
- src/frontend/components/UI/AuthModal/index.tsx
- src/frontend/state/authState.ts
After import, HyperPlay reloads. This reopens the Auth Modal if the user was in the middle of the auth flow
We still need to handle setting `openAuthModalIfAppReloads` to false after connection or if the auth flow is abandoned by the user
@eliobricenov 
---
> Reopen auth modal on app reload after import

- src/frontend/state/libraryState.ts
Fix #599 
1. On the library, click on Add Game
2. Select Browser as platform
3. Add Xcloud to the title
4. For the URL add `https://xbox.com/play`
5. Click on Finish
6. Restart HyperPlay
7. The Added App should still show on the library
---
> [FIX] Sideloaded apps not showing after restart

- .github/workflows/release_windows.yml
Replace GetRelease action with [ReleaseAction](https://github.com/marketplace/actions/create-release) to fix 404 while getting the current release.
---
> [CI-FIX] Fix Windows Workflow GH Action

- src/frontend/assets/hyperplay/index.tsx
- src/frontend/screens/Login/index.tsx
- src/frontend/screens/Onboarding/analytics/index.tsx
- src/frontend/screens/Onboarding/index.module.scss
- src/frontend/screens/Onboarding/walletSelection/index.module.scss
- src/frontend/screens/Onboarding/walletSelection/index.tsx
- src/frontend/screens/Onboarding/welcome/index.tsx
Old logo was ~8KB and took >20ms to render. The new logo is ~0.8KB
HP UI logo is identical visually as well (bottom is from hp ui, top is the 8KB deleted one)
> [Tech] Replace HP colored logo with optimized version

- src/frontend/App.tsx
- src/frontend/components/UI/TopNavBar/index.tsx
- src/frontend/constants.ts
- src/frontend/screens/Library/components/LibraryTopBar/index.tsx
- src/frontend/screens/Login/index.tsx
Added a feature flag from LaunchDarkly to replace the current hardcoded constant for enabling/disabling the Amazon Games integration:
[amazon-store-feature-flag.webm](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/26871415/0ad8c7ef-5c12-4ef0-978a-8f1c4ef034c8)
---
> [FEAT] Add feature flag for Amazon Store integration

- src/frontend/components/UI/ErrorComponent/index.tsx
- src/frontend/components/UI/Sidebar/components/SidebarLinks/index.tsx
- src/frontend/screens/Login/index.tsx
- src/frontend/state/GlobalState.tsx
- src/frontend/state/libraryState.ts
This fixes the issue with HP not checking for game updates on startup, leading users to play outdated games unless they hit the refresh button.
`checkUpdates` option is now `true` by default on all places and set to `false` only on the places we do not need it, like on a new login and browsing around.
- With games in need to update for any library, check if you can reproduce the issue on the stable release or main branch.
- When opening the library no game will show that it needs update, only after hitting the refresh button.
- Open the library again on this build and check if you can see the update icon on the game after the refresh finishes.
---
> [FIX] Check for games updates on startup

- src/frontend/screens/Game/GamePage/index.tsx
Remove the cloud saves info for HP and Sideloaded games on game page since it is not useful.
---
> [FIX] Don't show Cloud Saves for HP and Sideloaded Games

- src/backend/api/library.ts
- src/frontend/screens/Game/GamePage/index.tsx
- src/frontend/state/GlobalState.tsx
- src/frontend/state/libraryState.ts
- Fix the Game Page not updating right after uninstalling an HP game.
- Fix tracking of uninstalling HP Games.
This was due to HP games calling `removeApp` instead of `uninstall`, so it was skipping the tracking and the status update.
But I also changed some other few lines to make the process more resilient and the HP library refreshes quicker.
- On stable release or main branch, uninstall a HyperPlay game.
- Checks That there is no notification and the page take several seconds to update the status
- On this branch it will be a notification and the page will update instantly just like the games from other Stores.
---
> [FIX] Uninstall Status for HP Games

- src/backend/storeManagers/hyperplay/games.ts
This PR adds a method called `writeManifestFile` that creates a file with basic info for the installed game so we can use it to properly import previously installed games.
- Call the method on Game Install
- Call the method on Game Update
- Call the method on `getGameInfo` to update currently installed games (temporary)
- For installed games, after opening HP and going to the library or the game page, a new file should appear on the game install folder called `appName.json` (eg.: `0xf544a85580b166cc656be3015bde2a5eba4fa832867a04a45b49a87d2e374af5.json`. It won't be on the actual folder with the game files but on the parent folder with the developer name.
- For new installs, the file should appear just after the installation.
```
{
"appName": …
```
> [TECH] Add writeManifestFile function to write manifest.json file

- src/frontend/helpers/library.ts
- src/frontend/screens/Game/GamePage/index.tsx
- src/frontend/screens/Library/components/GameCard/index.tsx
Update GamePage and Gamecard to ignore the force update when testing with QA Mode.
---
> [TECH] Skip update on QA Mode

- src/backend/storeManagers/hyperplay/games.ts
Download into a .temp folder in the default install path by default. If the default install path setting is not set, use the config folder as was used previously
---
> [UX] Use download folder install path for .temp

- src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
Fixes space available calculation to download size + uncompressed size to match the new behavior in https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/pull/742
---
> [Fix] Space available calculation

- src/backend/storeManagers/hyperplay/games.ts
Move the download install directory inside the destination directory so all downloads and extractions happen on the same directory for accurate space requirements estimates
---
> [UX] Install to .temp in game destination directory

- flathub/update-flathub.ts
- package.json
- yarn.lock
Fix the current issues:
- Workflow failed to add release notes and open the PR because the structure of the original XML changed due to Flathub made it mandatory to add a Copyright comment at the top. So I adjusted the position of the `ul` element to the correct one.
- Moved from xml2js over to fast-XML-parse that is the most updated lib and doesn't mess with formatting.
Tested it running the command locally and the result can be observed on this PR:
https://github.com/flathub/xyz.hyperplay.HyperPlay/pull/80
---
> [FIX] Flathub release workflow

- src/backend/utils.ts
- src/backend/wine/manager/ipc_handler.ts
- src/backend/wine/manager/utils.ts
Wine was being installed on Windows, making the app slow to launch
---
> [Fix] Prevent wine install on windows

- src/backend/downloadmanager/utils.ts
Fixes the 'Game Install Failed' to only trigger when `status === 'error'`.
Right now it was being sent also for when it was aborted so canceling or pausing the downloads were triggering failed as well.
There is also another event for Abort that is not related with this one, this one tracks the Failed event and should be triggered only on `error`.
---
> [FIX] Install Event Tracking

- src/backend/main.ts
- src/backend/metrics/types.ts
This was giving `fetch failed` on HyperPlay startup and in general does not need to be active until the Summon quest is live
> [Summon Quest] Add LD flag, error handling, metrics events

- vite.config.ts
Fix an issue introduced after migrating to Vite5 where the check-disk-space library was not working correctly. So the calculation was failing on the install modal.
---
> [FIX] Check disk space not working

- src/backend/main.ts
There is an issue with `src/backend/main.ts` being bundled twice. This is due to `frontendReady` being imported by a submodule
You can see that the `ipcMain.handle("callTool"...` is included twice
And the download queue (and other code more than likely) is called twice. for example:
```
(14:30:05) INFO:    [Backend]:          Starting the Download Queue
(14:30:05) INFO:    [Backend]:          Starting the Download Queue
```
After this PR's changes, this becomes
```
(14:30:05) INFO:    [Backend]:          Starting the Download Queue
```
`frontendReady` is only being used in this one place so moving it to the submodule does not break any other code
> [Fix] Move frontend ready

- .github/workflows/release_macOS.yml
- .github/workflows/release_windows.yml
Change node version to 18
Add force to overwrite previous version of same name for windows on signpath
> [CD Fix] Mac release node version & add windows signpath force flag

- src/frontend/OverlayManager/index.module.scss
- src/frontend/OverlayManager/index.tsx
- src/frontend/components/UI/WebviewControls/index.tsx
Adds go back and go forward arrow icon buttons to browser games.
I attempted to set the disabled boolean based on `webview.canGoBack` but there was an issue attempting to use `webview.current` before the `"dom-ready"` event had fired. Correct me if I'm wrong, but I don't think this is a blocker.
https://app.qase.io/project/HC?case=332&previewMode=modal
> [Feat] Add go back and go forward arrows to browser games

- src/backend/api/misc.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/backend/storeManagers/index.ts
- src/backend/storeManagers/sideload/library.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/state/libraryState.ts
I've noticed that when I am logged in on all stores with more than 550 games the first loading takes almost a minute to show the games. This is due to how slow checking for game updates is since it iterates through all runners and wait for each list to complete to then full-fill the promise, so longer the library slower it will be.
So I did a few small changes:
- Added the a `Runner[]` parameter to `checkGameUpdates`.
- Await only for the list of HyperPlay games, so will only block the thread for these.
- Call it again for the rest of the runners but without blocking the thread.
This way the behaviour will be:
- The list of games will appear right away since the hyperplay request is quite fast.
- All other games from other stores will load but the update status for the games will only …
> [TECH] Speed Up Big Libraries loading

- package.json
- yarn.lock
Upgrade ethers so it can handle `eth_getTransactionByHash` not returning `signature` with MetaMask extension, fixed in 6.9.1. We were previously on ethers 6.9.0
> [Fix] Upgrade ethers to fix MM extension incompatibility

- package.json
- src/frontend/App.tsx
- src/frontend/screens/Onboarding/walletSelection/screens/import/components/ImportAndCreateOptions/index.tsx
Direct linking to SRP page results in a new wallet being created instead of importing from the SRP. Clicking create new wallet and then importing SRP starting from the first page works though.
> [Fix] Remove SRP direct link option

- package.json
- src/backend/proxy/providerPreload.ts
Add deprecated provider on topics for backwards compatibility. Return result directly from send
https://app.qase.io/project/HC?suite=61&case=346&previewMode=modal
> [Fix] Compatibility with deprecated on topics and fix send request return for browser game provider

- package.json
- src/backend/storeManagers/hyperplay/library.ts
- change `console.error` to `logError` so that error message can be seen in production for channel names that were changed or removed
- early return so that library refresh does not get stuck if a library game is in this state
> [Tech] Fix channel logs

- src/backend/launcher.ts
Previously, there was a bug where closing the overlay and then the game would throw when `hpOverlay?.closeOverlay()` was called in `child.on('close'`. This would cause play sessions to not be posted correctly on game close. This could happen if the user pressed alt+f4 twice with the overlay over the game for instance.
This PR adds a try catch to the close overlay call so that the rest of the 'launch' handler will execute under these circumstances.
> [Fix] add try catch to close overlay

- src/backend/storeManagers/hyperplay/games.ts
This fixes an edge case where the isGameAvailable command fails to work if there is backslashes in a windows game executable path on mac and linux.
Game affected so far: The Unfettered: Awakening.
---
> [FIX] isGameAvailable fail because of backslashes for windows games on mac and linux

- src/frontend/state/GlobalState.tsx
This will show a warning dialog to the user if they try to close the app while a game is running. 
It is the same copy and options as we have for when a game is being downloaded.
We can trick this in the future if needed.
- Launch any game
- While the game is opened, try to close hyperplay
- A warning should appear.
---
> [FEAT] Show warning on close the app if a game is opened.

- package.json
- src/frontend/hooks/useGetRewards.ts
- Fixes a bug where rewards with decimals = 0 won't display the amount to claim
> [Fix] Decimals null check in useGetRewards

- src/frontend/screens/Game/GamePage/index.tsx
- yarn.lock
I noticed that the Wallet Onboard modal was showing up when launching games from the library but not showing up when launching games from the game page.
Since now most people are using the game page due to redirect I think this should be fixed.
---
> [FIX] Show Wallet onboard when launching web3 game from GamePage

- public/locales/en/translation.json
- src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
- if the GET quests request fails, this message modal will show
> [Fix] no quests message

- src/backend/api/library.ts
- src/backend/launcher.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/backend/storeManagers/hyperplay/utils.ts
- src/backend/storeManagers/legendary/games.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/helpers/index.ts
- src/frontend/screens/Game/GamePage/index.tsx
- src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
FIX #990 by  adding some methods to get the epic url from the API and checking it with the epic games on the use library then navigating either to the library page (when the game is on the library) or to the epic games store page.
---
> [FIX] Deal with Epic games listing from Quests Page

- src/common/types.ts
- src/frontend/hooks/useGetRewards.ts
Fix `numClaimsLeft` for erc1155 rewards
Check xociety crates (ERC1155). number of claims left should be 10000
Bushi (ERC721) should still read 125
Other rewards (ERC20) should still show correctly if assets have been deposited
> [Fix] erc1155 numClaimsLeft

- .github/workflows/test-e2e-dev.yml
- .github/workflows/test-e2e-packaged.yml
The e2e tests are notoriously flaky, time-consuming/difficult to write, and haven't caught many bugs to date. Let's disable them for now until this implementation is more robust and the developer experience is acceptable.
> [CI] disable e2e tests

- src/backend/downloadmanager/downloadqueue.ts
- src/backend/storeManagers/hyperplay/library.ts
- src/frontend/screens/Game/GamePage/index.tsx
Should fix an issue where the Game fails to download or is stuck in the queue because the default channel is different from  `main`. 
So it was defaulting to `main` on `addDMToQueue` and then `release_meta` was coming as `undefined`.
Tested installing games that has only one main channel like Darkthrone, games that has two channels like Bushi and Code: Havoc that has only the Alpha channel and no main channel.
---
> [FIX] HyperPlay fails if the game default channel is not expected

- src/frontend/screens/Library/components/GameCard/index.tsx
Small fix to a bug I just found where we can access the game settings for Browser games.
Before:
After:
---
> [FIX] Don't show Game Settings for Browser games on game card

- src/common/types.ts
- src/frontend/screens/Library/components/GameCard/index.tsx
- src/frontend/screens/Library/components/GamesList/index.tsx
- src/frontend/state/GlobalState.tsx
- src/frontend/state/__tests__/libraryState.test.ts
- src/frontend/state/libraryState.ts
This PR
- fixes hide, unhide, favorite and unfavorite
- previously favorite and unhide would not work on refresh or app restart. taking any action would revert the hidden game as well
- moves this functionality into library state and adds a test for it
> [Fix] hide, unhide, favorite, and unfavorite game

- .vscode/settings.json
- public/locales/en/gamepage.json
- src/backend/storeManagers/hyperplay/utils.ts
- src/frontend/screens/Game/GamePage/index.tsx
- src/frontend/screens/Library/components/GameCard/index.tsx
- src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
Fix issue that is making games like The Unfettered: Awakening not loading info on the Game Page because it received `webgl` as game platform but the client doesn't understand it.
Other games that have a `WebGL` platform on the dev portal might be affect as well.
So Far, only game affected is The Unfettered: Awakening.
Simply add the game to your library and try to go to the game page.
On `main` it will show an error screen:
On This branch it should load the page just fine:
Installation should work just fine as well.
---
> [FIX] Get Install Info failing because of WebGL platform

- package.json
- src/backend/storeManagers/hyperplay/library.ts
Fix issues like we had now with The Unfettered Awakening where players got the update available notification but the original build was removed only leaving the web one.
QASE Test: https://app.qase.io/project/HC?suite=39&previewMode=modal&case=366
---
> [FIX] Don't update games with removed platform build

- src/backend/utils.ts
Fix `getPlatformName` platform tracking for sideloaded games.
---
> [FIX] Unknown platform name on sideload launch

- package.json
- src/frontend/ExtensionManager/components/ExtensionContents/index.tsx
- src/frontend/ExtensionManager/index.tsx
- src/frontend/OverlayManager/Overlay/index.module.scss
With the update to the overlay layout, there was a regression in the MM window, and now, when the overlay is open and there is a transaction request, we don't show the notification popup automatically, closing and re-opening the overlay is needed.
You can test this in dev mode in `main` by connecting your wallet and requesting a signature from the console:
```
await window.ethereum.request({
method: 'personal_sign',
params: ['Hi', (await window.ethereum.request({ method: 'eth_requestAccounts' }))[0]]
});
```
---
> fix(overlay): show notification window on transaction request

- package.json
- src/backend/storeManagers/hyperplay/utils.ts
Fix overlay not showing for some epic forwarder listings. Use `project_meta.name` to match on title from now on.
> [Fix] Fix overlay not showing for some epic fwd listings

- package.json
- src/frontend/OverlayManager/Overlay/index.module.scss
- src/frontend/OverlayManager/Overlay/index.tsx
- src/frontend/OverlayManager/index.tsx
- src/frontend/components/UI/QuestsViewer/index.tsx
- src/frontend/helpers/getPlaystreakArgsFromQuestData.ts
- src/frontend/screens/Quests/components/QuestDetailsViewPlay/index.tsx
- yarn.lock
Pulls in https://github.com/HyperPlay-Gaming/quests-ui/pull/18
Previously the `Overlay` was conditionally rendered on overlay toggle, causing re-renders that reset the sync timer. Now the overlay is hidden but not removed from the DOM so that the sync hooks won't reset on overlay toggle.
https://app.qase.io/project/HC?suite=75&previewMode=modal&case=368
> [Fix] Sync playsession for non-hp runners

- .github/workflows/build.yml
- .github/workflows/release_linux.yml
With the update to jammy, we needed to run `sudo apt-get update` first before installing `libarchive-tools`
> [Tech] Fix linux build

- src/frontend/screens/Quests/components/QuestsSummaryTableWrapper/index.tsx
closes https://github.com/HyperPlay-Gaming/product-management/issues/517
1. Go to the quests page 
2. Click on a card
3. Observe that the gradient border remains on that card even when not hovering it
> [UI] show gradient border on quest card selected

- src/backend/config.ts
- src/backend/updater.ts
Since we update to the latest version of electron-updater it enabled auto-update for DEB. RPM and PACMAN. The problem is that it is not stable on all distros and also we already publish the pacman file on AUR so it conflicts with the ARCH updates.
There are also some cases where it needs elevation but the distro won't ask for it.
So we should disable it for now until we test this feature a bit more.
---
> [TECH] Disable Auto-Update for Linux binaries (for now)

- src/frontend/screens/Quests/index.tsx
part of https://github.com/HyperPlay-Gaming/product-management/issues/717
I didn't delete `G7CreditsModal` since I think it will be used again in future G7 events
> [Chore] Remove g7 credits modal

- src/frontend/components/UI/QuestsViewer/index.module.scss
When logged out of HP, the quests viewer div was overflowing the page and the whole overlay was scrollable.
This keeps the container within the viewport and keeps the scrolling only inside the content of the quests viewer.
> [Fix] UI - overflow of quests container when logged out in overlay

- src/backend/proxy/providerPreload.ts
closes https://github.com/HyperPlay-Gaming/product-management/issues/765
Ethers has several situations where it throws an error like the following
```
Error: could not coalesce error (error={ "code": 4902, "message": "Unrecognized chain ID \"0x144\". Try adding the chain using wallet_addEthereumChain first." }, payload={ "id": 13, "jsonrpc": "2.0", "method": "wallet_switchEthereumChain", "params": [ { "chainId": "0x144" } ] }, code=UNKNOWN_ERROR, version=6.13.2)
```
e.g. https://github.com/ethers-io/ethers.js/issues/4576
The above error was generated when trying to switch chains. Because `makeError` fails at `ethers\lib.commonjs\utils\errors.js`, the error object is not correctly formed. We can parse the error object out of the error string as a fallback here.
Note that since this error …
> [Fix] Network add in portfolio swap

- package.json
- src/backend/main.ts
- src/backend/utils/quests.ts
Fix an issue where the game status won't change after finishing playing and the player is not logged in on HyperPlay.
The issue was because it was getting stuck on the `syncPlaySession` method and was never triggering the `gameStatusUpdate` with the `done` status.
Moved this one to be above the playtime and also added some `try/catch` to the sync methods.
---
> [FIX] Update Game status after finishing playing and not logged in

- src/frontend/components/UI/LanguageSelector/index.tsx
- src/frontend/screens/Onboarding/welcome/index.tsx
A global class intended for the lang selector in settings was breaking the lang selector on the welcome modal at screen sizes <850px
Before
After
> rm global class from weclome modal lang selector

- public/locales/en/translation.json
- src/backend/tools.ts
- src/frontend/screens/Library/components/SteamInstall/SteamInstallDialog.tsx
Since Steam moved to a new version of CEF (Chromium), it broke completely when using through the Gaming porting toolkit.
I changed the Steam source to be the latest version of Steam with the old CEF, that still works fine, and since this is not a Installation setup anymore, needed to change how we install it and, with it, some dialogs needed to be changed as well.
- Uninstall your Steam installation on macOS if you have it.
- Reinstall Steam using the Install Steam button on the library
- Launch Steam after installing it and login to see if it will work fine and load the library.
---
> [FIX] Steam on macOS not launching

- public/locales/en/translation.json
- src/frontend/components/UI/AppVersion/index.tsx
- src/frontend/components/UI/TopNavBar/index.module.scss
- src/frontend/components/UI/TopNavBar/index.tsx
- src/frontend/screens/Settings/sections/GeneralSettings/index.tsx
<--- Description --->
This is a small update on our version badge on the Store, changed from Alpha to a dynamic version number, and also removed the version number on the settings page as we will have this in a more prominent place now. 
---
> [UI] renamed public alpha to a dynamic version number on the Store

- src/backend/api/library.ts
- src/backend/main.ts
- src/backend/storeManagers/hyperplay/games.ts
- src/common/typedefs/ipcBridge.d.ts
- src/frontend/helpers/library.ts
- src/frontend/screens/Library/components/InstallModal/DownloadDialog/index.tsx
- src/frontend/screens/Library/components/InstallModal/ModDialog/index.tsx
This PR fixes
- update of token gated games
- install of token gated games with non mm extension wallets
request siwe logic is moved to main process so that the request goes to the currently connected provider, not just the injected provider on the main window
closes https://github.com/HyperPlay-Gaming/product-management/issues/837
> [Fix] Token gated games install/update

- .github/workflows/release_macOS.yml
arm64 release step is failing with `pnpm: command not found`
https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/actions/runs/12405186947/job/34631594238
> [Fix] arm64 release gha

- src/backend/storeManagers/hyperplay/games.ts
url is handled differently in node.js than in the browser, leading to a bug where requestSIWE was not working in the packaged artifact
> [Fix] SIWE check in packaged app

- src/backend/images_cache.ts
URLs were being passed over file protocol like `https//gateway.valist.io/ipfs/bafybeig57jh3x3q2vlmctjsdkx6yx36n4uza2rsp373suwlzcs2bgxkpbe` without the colon.
This was causing axios to throw a `Invalid URL` unhandled error on every `CachedImage` component render. This also broke the image caching functionality at `imagesCachePath`.
See https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/1732 for more context on the original implementation.  
We may be able to use https://www.electronjs.org/docs/latest/api/command-line-switches#--disk-cache-sizesize, which was suggested here https://github.com/electron/electron/issues/7713, for the same use case in the future as well instead of a custom caching implementation.
Closes https://github.com/HyperPlay-Gaming/product-management/issues …
> [Fix] Invalid URL error and image caching

- src/frontend/helpers/index.ts
This should fix issues like we had with the Rat game.
- On Linux and macOS only
- Install the RAT RACE COMBAT game
- Try to run it using any compatibility layer version
- The game should launch
In the current release the game won't launch because there is a `space` at the end of the generated prefix folder.
---
> [Fix] Remove Spaces from the Wine Prefix Folder

- src/frontend/screens/Quests/index.tsx
At the moment the Quest Page search bar only searches by the quest title. In addition, I added keyword search logic, mainly for the YGG banner logic (and possibly future ones). This is temporary until we implement fuzzy search on the Quest Page as we do on the Store Page search.
---
> [feat] Enhance quest search functionality with multi-keyword search

- public/locales/en/gamepage.json
- src/frontend/screens/Library/components/GameCard/index.tsx
This PR adds the tooltip for the Store icons in the Library that was added on hyperplay-ui before, now being rendered on the client. 
---
> (feat) update on hover state the the store icons on library

- src/backend/downloadmanager/utils.ts
- src/backend/ipcHandlers/mods.ts
- src/backend/services/ExtractZipService.ts
- src/backend/services/__tests__/ExtractZipService.test.ts
- src/backend/storeManagers/hyperplay/games.ts
This is breaking the store while extracting, and we don't have any electron games, so let's feature flag it
closes https://github.com/HyperPlay-Gaming/px-pm/issues/112
> [Fix] rm process.noAsar changes

- src/backend/main.ts
- src/common/types/electron_store.ts
This is a new approach from #1249.
This pull request includes several changes to the `src/backend/main.ts` and `src/common/types/electron_store.ts` files to handle app version updates and ensure proper functionality when the app version changes. The changes primarily focus on checking the app version and reloading the app if the version has changed.
* [`src/backend/main.ts`](diffhunk://#diff-859af3c776da914ebff60fa13adfc96e79d99ea563fe1e4e790de14656442accR473-R483): Added logic to compare the current app version with the stored version and log the change. If the app version has changed, the new version is stored.
* [`src/backend/main.ts`](diffhunk://#diff-859af3c776da914ebff60fa13adfc96e79d99ea563fe1e4e790de14656442accR720-R735): Added a check in the `ipcMain.once('frontendReady', async …
> [FIX] Reload app due to extension only on app update 

- src/frontend/components/UI/DownloadToastManager/index.tsx
This changes how we get the Download Size depending on the status, right now it uses download status for both install and extracting. 
It also adds a safeguard to the Download Toast so it won't show a Downloaded size bigger than Total Download Size. Might not be needed but it is 'just in case' since our numbers might not be precise sometimes.
https://github.com/user-attachments/assets/dfc178a2-93d0-463a-b349-991159cdb7f9
---
> [FIx] Edge case where downloaded size is bigger than download size

- public/locales/en/translation.json
- src/frontend/components/UI/AccountDropdown/index.tsx
- Changed "Swap wallet account" label to "Swap connected wallet"
- Changed "changeWallet" i18n token to "swapConnectedWallet"
Closes https://github.com/HyperPlay-Gaming/px-pm/issues/280
> Change swap wallet terminology

- src/backend/main.ts
- src/common/types/electron_store.ts
Failing this test case
1. launch hp
2. create mm ext wallet and connect
3. close hp
4. open hp
5. try to connect wallet but no connection is made
> Revert "[FIX] Reload app due to extension only on app update  (#1261)"

- package.json
- src/frontend/components/UI/QuestDetails/index.tsx
We were returning an object on set active wallet sign rejection and sending {} to the api for signature causing InvalidSignature during the set active wallet flow
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/578
> [Fix] Add action rejected check to set active wallet

- src/frontend/components/UI/QuestsViewer/index.tsx
update the not logged in alert in the overlay to match the quests page alert by not showing the close button since it is not dismissable
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/647
> [Fix] Overlay alert banner close button

- package.json
- pnpm-lock.yaml
closes https://github.com/HyperPlay-Gaming/hyperplay-pm/issues/334
https://app.qase.io/case/HC-327 with MetaMask extension installed via a native package manager on linux
> [Fix] Extension import for native linux package managers

- package.json
- pnpm-lock.yaml
Left align quest details cta on the quests page
Note that this also brings in https://github.com/HyperPlay-Gaming/hyperplay-ui/pull/537 but `Poppins` seems to be imported correctly even without adding another `import '@hyperplay/ui/fonts.css'`.
> [UI] Left align quest details cta
